### ISSUE TITLE
Restrictive dependency on puppetlabs/apt

### ISSUE THREAD

**Issue by optiz0r** [bodgit/puppet-zfs#11]
The dependency on `puppetlabs-apt<5` is blocking stdlib being updated beyond 4.25.1. stdlib only officially supports puppet 6 from v5.1 and newer versions contain useful fixes. 

Tests pass when the module dependency is updated to `<8`, however since I don't use this module on any apt-based systems, I can't provide any more testing than that.

**Comment by bodgit** [comment]
I've uploaded version 2.2.4 which should have this fix plus a few other small unreleased changes. Thanks for the contribution!
