### ISSUE TITLE
CentOS 7.4

### ISSUE THREAD

**Issue by ianssoftcom** [bodgit/puppet-zfs#6]
I have found that with the current kernel from 7.4 that a new zfs-release file is needed specific to that version:
http://download.zfsonlinux.org/epel/zfs-release.el7_4.noarch.rpm

I see that in manifests/install.pp the zfs-release file of zfs-release.el7.noarch.rpm is installed, but I'm finding that the 7_4 version is needed now with the current '3.10.0-693' kernels.

`$_source = "http://download.zfsonlinux.org/epel/zfs-release.el${::operatingsystemmajrelease}.noarch.rpm"`

Can you think of a good way to handle this other than write an if statement (if version is >= 7.3, then install the _$facts['os']['release']['minor]' version?

**Comment by bodgit** [comment]
It looks like there are release packages for 6, 7, 7.3, and 7.4 currently, although I don't yet know if 7.5 will get its own release package or not, I can only assume so. I will commit a fix for this shortly.

**Comment by bodgit** [comment]
Version v2.2.2 should be up on the forge with this fix. Thanks for the bug report!
