### ISSUE TITLE
Does not install the kernel modules on Debian

### ISSUE THREAD

**Issue by tullis** [bodgit/puppet-zfs#7]
Hi and thanks for your work on this module.

I notice that it doesn't actually install the `zfs-dkms` package on Debian 9, which would be really useful.

**Comment by bodgit** [comment]
Did you see the note in the README for Debian 9? You need to enable the contrib repository with something like:
```puppet
::apt::source { 'contrib':
  location => 'http://deb.debian.org/debian',
  repos    => 'contrib',
}
```
From memory I found it wouldn't install the dkms bits otherwise. If you have done that and it still doesn't work, let me know.

**Comment by tullis** [comment]
Thanks for your reply.

Yes, I have the contrib repository enabled. I believe that the problem is that the zfsutils-linux package only **recommends** the zfs-dpks package. I have an apt preference not to install recommended packages, which is why it didn't pull it in automatically. Otherwise I think it would have worked.

```
ben@server:~$ apt depends zfs-dkms
zfs-dkms
  PreDepends: spl-dkms (>= 0.6.5.9)
  Depends: dkms (>> 2.1.1.2-5)
  Depends: lsb-release
 |Depends: debconf (>= 0.5)
  Depends: <debconf-2.0>
    cdebconf
    debconf
  Recommends: zfsutils-linux
  Recommends: zfs-zed
```

**Comment by bodgit** [comment]
I will likely change the `package_name` parameter to also take an array which can then be set to `['zfsutils-linux', 'zfs-dkms']`. The `zfs-zed` recommendation is covered already by the `::zfs::zed` class.

**Comment by bodgit** [comment]
@tullis I've been meaning to ask, would you mind sharing with me how you configured apt to not install recommended packages (presumably you've done it with the apt Puppet module somehow and I'm not a Debian user). I'd like to add it to my acceptance tests going forward so it catches things like this.

**Comment by tullis** [comment]
Until now I have been doing it with a simple file resource in puppet that manages an apt_preferences fragment.

```
  file { '/etc/apt/apt.conf.d/50disable-recommends':
    ensure => present,
    owner  => 'root',
    group  => 'root',
    mode   => '0644',
    source => 'puppet:///modules/base/50disable-recommends',
  }
```

That fragment file contains the following:
```
APT::Install-Recommends "false";
APT::Install-Suggests "false";
```

I am planning to change it to use an [apt::setting](https://forge.puppet.com/puppetlabs/apt#defined-type-aptsetting) type, but I haven't got round to it yet.

**Comment by bodgit** [comment]
Sorry for the delay fixing this, I've pushed v2.2.3 to the forge which now works on Debian if you have APT configured to not install recommended packages. Thanks for the bug report!
